# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import word_count_pb2 as word__count__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in word_count_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DistributedWordCountStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BroadcastNodeCounts = channel.unary_unary(
                '/wordcount.DistributedWordCount/BroadcastNodeCounts',
                request_serializer=word__count__pb2.NodeCounts.SerializeToString,
                response_deserializer=word__count__pb2.Empty.FromString,
                _registered_method=True)
        self.AssignRange = channel.unary_unary(
                '/wordcount.DistributedWordCount/AssignRange',
                request_serializer=word__count__pb2.LetterRange.SerializeToString,
                response_deserializer=word__count__pb2.Empty.FromString,
                _registered_method=True)
        self.MulticastLine = channel.unary_unary(
                '/wordcount.DistributedWordCount/MulticastLine',
                request_serializer=word__count__pb2.DocumentLine.SerializeToString,
                response_deserializer=word__count__pb2.Empty.FromString,
                _registered_method=True)
        self.SubmitCounts = channel.unary_unary(
                '/wordcount.DistributedWordCount/SubmitCounts',
                request_serializer=word__count__pb2.WordCounts.SerializeToString,
                response_deserializer=word__count__pb2.Empty.FromString,
                _registered_method=True)
        self.SubmitValidatedCounts = channel.unary_unary(
                '/wordcount.DistributedWordCount/SubmitValidatedCounts',
                request_serializer=word__count__pb2.WordCounts.SerializeToString,
                response_deserializer=word__count__pb2.Empty.FromString,
                _registered_method=True)
        self.EndDocument = channel.unary_unary(
                '/wordcount.DistributedWordCount/EndDocument',
                request_serializer=word__count__pb2.Empty.SerializeToString,
                response_deserializer=word__count__pb2.Empty.FromString,
                _registered_method=True)
        self.RegisterNode = channel.unary_unary(
                '/wordcount.DistributedWordCount/RegisterNode',
                request_serializer=word__count__pb2.NodeInfo.SerializeToString,
                response_deserializer=word__count__pb2.Empty.FromString,
                _registered_method=True)


class DistributedWordCountServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BroadcastNodeCounts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MulticastLine(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitCounts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitValidatedCounts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DistributedWordCountServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BroadcastNodeCounts': grpc.unary_unary_rpc_method_handler(
                    servicer.BroadcastNodeCounts,
                    request_deserializer=word__count__pb2.NodeCounts.FromString,
                    response_serializer=word__count__pb2.Empty.SerializeToString,
            ),
            'AssignRange': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignRange,
                    request_deserializer=word__count__pb2.LetterRange.FromString,
                    response_serializer=word__count__pb2.Empty.SerializeToString,
            ),
            'MulticastLine': grpc.unary_unary_rpc_method_handler(
                    servicer.MulticastLine,
                    request_deserializer=word__count__pb2.DocumentLine.FromString,
                    response_serializer=word__count__pb2.Empty.SerializeToString,
            ),
            'SubmitCounts': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitCounts,
                    request_deserializer=word__count__pb2.WordCounts.FromString,
                    response_serializer=word__count__pb2.Empty.SerializeToString,
            ),
            'SubmitValidatedCounts': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitValidatedCounts,
                    request_deserializer=word__count__pb2.WordCounts.FromString,
                    response_serializer=word__count__pb2.Empty.SerializeToString,
            ),
            'EndDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.EndDocument,
                    request_deserializer=word__count__pb2.Empty.FromString,
                    response_serializer=word__count__pb2.Empty.SerializeToString,
            ),
            'RegisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterNode,
                    request_deserializer=word__count__pb2.NodeInfo.FromString,
                    response_serializer=word__count__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wordcount.DistributedWordCount', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('wordcount.DistributedWordCount', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DistributedWordCount(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BroadcastNodeCounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wordcount.DistributedWordCount/BroadcastNodeCounts',
            word__count__pb2.NodeCounts.SerializeToString,
            word__count__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wordcount.DistributedWordCount/AssignRange',
            word__count__pb2.LetterRange.SerializeToString,
            word__count__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MulticastLine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wordcount.DistributedWordCount/MulticastLine',
            word__count__pb2.DocumentLine.SerializeToString,
            word__count__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitCounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wordcount.DistributedWordCount/SubmitCounts',
            word__count__pb2.WordCounts.SerializeToString,
            word__count__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitValidatedCounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wordcount.DistributedWordCount/SubmitValidatedCounts',
            word__count__pb2.WordCounts.SerializeToString,
            word__count__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wordcount.DistributedWordCount/EndDocument',
            word__count__pb2.Empty.SerializeToString,
            word__count__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wordcount.DistributedWordCount/RegisterNode',
            word__count__pb2.NodeInfo.SerializeToString,
            word__count__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
