# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: word_count.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'word_count.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10word_count.proto\x12\twordcount\"{\n\nNodeCounts\x12\x11\n\tproposers\x18\x01 \x01(\x05\x12\x11\n\tacceptors\x18\x02 \x01(\x05\x12\x10\n\x08learners\x18\x03 \x01(\x05\x12\x1a\n\x12\x61\x63\x63\x65ptor_addresses\x18\x04 \x03(\t\x12\x19\n\x11learner_addresses\x18\x05 \x03(\t\"L\n\x0bLetterRange\x12\x14\n\x0cstart_letter\x18\x01 \x01(\t\x12\x12\n\nend_letter\x18\x02 \x01(\t\x12\x13\n\x0bproposer_id\x18\x03 \x01(\t\"\x1f\n\x0c\x44ocumentLine\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"\x99\x01\n\nWordCounts\x12\x13\n\x0bproposer_id\x18\x01 \x01(\t\x12\x31\n\x06\x63ounts\x18\x02 \x03(\x0b\x32!.wordcount.WordCounts.CountsEntry\x1a\x43\n\x0b\x43ountsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.wordcount.WordCount:\x02\x38\x01\")\n\tWordCount\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x12\r\n\x05words\x18\x02 \x03(\t\"\x07\n\x05\x45mpty\")\n\x08NodeInfo\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t2\xbe\x03\n\x14\x44istributedWordCount\x12@\n\x13\x42roadcastNodeCounts\x12\x15.wordcount.NodeCounts\x1a\x10.wordcount.Empty\"\x00\x12\x39\n\x0b\x41ssignRange\x12\x16.wordcount.LetterRange\x1a\x10.wordcount.Empty\"\x00\x12<\n\rMulticastLine\x12\x17.wordcount.DocumentLine\x1a\x10.wordcount.Empty\"\x00\x12\x39\n\x0cSubmitCounts\x12\x15.wordcount.WordCounts\x1a\x10.wordcount.Empty\"\x00\x12\x42\n\x15SubmitValidatedCounts\x12\x15.wordcount.WordCounts\x1a\x10.wordcount.Empty\"\x00\x12\x33\n\x0b\x45ndDocument\x12\x10.wordcount.Empty\x1a\x10.wordcount.Empty\"\x00\x12\x37\n\x0cRegisterNode\x12\x13.wordcount.NodeInfo\x1a\x10.wordcount.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'word_count_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WORDCOUNTS_COUNTSENTRY']._loaded_options = None
  _globals['_WORDCOUNTS_COUNTSENTRY']._serialized_options = b'8\001'
  _globals['_NODECOUNTS']._serialized_start=31
  _globals['_NODECOUNTS']._serialized_end=154
  _globals['_LETTERRANGE']._serialized_start=156
  _globals['_LETTERRANGE']._serialized_end=232
  _globals['_DOCUMENTLINE']._serialized_start=234
  _globals['_DOCUMENTLINE']._serialized_end=265
  _globals['_WORDCOUNTS']._serialized_start=268
  _globals['_WORDCOUNTS']._serialized_end=421
  _globals['_WORDCOUNTS_COUNTSENTRY']._serialized_start=354
  _globals['_WORDCOUNTS_COUNTSENTRY']._serialized_end=421
  _globals['_WORDCOUNT']._serialized_start=423
  _globals['_WORDCOUNT']._serialized_end=464
  _globals['_EMPTY']._serialized_start=466
  _globals['_EMPTY']._serialized_end=473
  _globals['_NODEINFO']._serialized_start=475
  _globals['_NODEINFO']._serialized_end=516
  _globals['_DISTRIBUTEDWORDCOUNT']._serialized_start=519
  _globals['_DISTRIBUTEDWORDCOUNT']._serialized_end=965
# @@protoc_insertion_point(module_scope)
